# Generated by Django 4.2.17 on 2024-12-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_id',
        ),
    ]
