# Generated by Django 4.2.17 on 2024-12-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_rename_user_project_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='project',
            new_name='project_id',
        ),
    ]
