# Generated by Django 4.2.17 on 2024-12-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_rename_user_id_project_user_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='project_id',
            new_name='project',
        ),
    ]
