# Generated by Django 4.2.17 on 2024-12-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
