# Generated by Django 4.2.17 on 2024-12-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0010_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Informational', 'Informational')], default='Pending', max_length=20),
        ),
    ]
