# Generated by Django 4.2.17 on 2024-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0011_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded'), ('Informational', 'Informational'), ('Cleared', 'Cleared')], default='Pending', max_length=20),
        ),
    ]
